#ifndef GLOBAL_DEFINE_H
#define GLOBAL_DEFINE_H

//Configurações
#define IDADE_MINIMA 18
#define IDADE_MAXIMA 90
#define DATA_INICIO_EMPRESA "01/01/2018"
#define DATA_LIMITE_FUTURO "31/12/2031"

//Menu

//Interface
#define MAX_LINHA 103
#define MAX_CABECALHO 3

//Cadastro
#define MAX_VETOR 1000
#define MAX_STRING 70

#define KEY_STRING_SAIR "SAIR"
#define KEY_STRING_MUDAR "MUDAR"

//Cadastro Campos
//Cliente
#define MAX_CAMPO_NOME__CLIENTE 67
#define MAX_CAMPO_EMAIL__CLIENTE 40
#define MAX_CAMPO_ENDERECO__CLIENTE 61
#define MAX_CAMPO_NUMENDERECO__CLIENTE 5
#define MAX_CAMPO_COMPENDERECO__CLIENTE 24
#define MAX_CAMPO_BAIRRO__CLIENTE 40
#define MAX_CAMPO_CIDADE__CLIENTE 34

//Funcionário
#define MAX_CAMPO_NOME__FUNCIONARIO 45
#define MAX_CAMPO_EMAIL__FUNCIONARIO 40
#define MAX_CAMPO_ENDERECO__FUNCIONARIO 61
#define MAX_CAMPO_NUMENDERECO__FUNCIONARIO 5
#define MAX_CAMPO_COMPENDERECO__FUNCIONARIO 24
#define MAX_CAMPO_BAIRRO__FUNCIONARIO 40
#define MAX_CAMPO_CIDADE__FUNCIONARIO 34

#define MAX_CAMPO_NOMEFANTASIA__FORNECEDOR 58
#define MAX_CAMPO_EMAIL__FORNECEDOR 40
#define MAX_CAMPO_SITE__FORNECEDOR 30
#define MAX_CAMPO_ENDERECO__FORNECEDOR 61
#define MAX_CAMPO_NUMENDERECO__FORNECEDOR 5
#define MAX_CAMPO_COMPENDERECO__FORNECEDOR 24
#define MAX_CAMPO_BAIRRO__FORNECEDOR 40
#define MAX_CAMPO_CIDADE__FORNECEDOR 34



#endif
